//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Information_Management_System__SIMS_
{
    public partial class Admin_ManageFees
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.WebControls.Label lblPendingAmount;
        protected global::System.Web.UI.WebControls.Label lblPaidAmount;
        protected global::System.Web.UI.WebControls.HiddenField hfCourseFeeId;
        protected global::System.Web.UI.WebControls.DropDownList ddlProgramme;
        protected global::System.Web.UI.WebControls.DropDownList ddlCourse;
        protected global::System.Web.UI.WebControls.DropDownList ddlFeeSession;
        protected global::System.Web.UI.WebControls.TextBox txtAmount;
        protected global::System.Web.UI.WebControls.Button btnSaveCourseFee;
        protected global::System.Web.UI.WebControls.Button btnClearCourseFee;
        protected global::System.Web.UI.WebControls.Button btnBack;
        protected global::System.Web.UI.WebControls.GridView gvCourseFees;
        protected global::System.Web.UI.WebControls.DropDownList ddlPaymentSession;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.GridView gvPayments;
    }
}
