//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Information_Management_System__SIMS_.Admin
{
    public partial class Reports
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.WebControls.Label lblTotalStudents;
        protected global::System.Web.UI.WebControls.Label lblActiveEnrollments;
        protected global::System.Web.UI.WebControls.Label lblAttendanceRecords;
        protected global::System.Web.UI.WebControls.DropDownList ddlReportType;
        protected global::System.Web.UI.WebControls.DropDownList ddlSession;
        protected global::System.Web.UI.WebControls.DropDownList ddlProgramme;
        protected global::System.Web.UI.WebControls.DropDownList ddlCourse;
        protected global::System.Web.UI.WebControls.Button btnGenerate;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Button btnBack;
        protected global::System.Web.UI.WebControls.Label lblReportTitle;
        protected global::System.Web.UI.WebControls.Label lblGeneratedAt;
        protected global::System.Web.UI.WebControls.Panel pnlPerformanceComingSoon;
        protected global::System.Web.UI.WebControls.Panel pnlExport;
        protected global::System.Web.UI.WebControls.LinkButton btnExportCsv;
        protected global::System.Web.UI.WebControls.LinkButton btnExportExcel;
        protected global::System.Web.UI.WebControls.LinkButton btnExportPdf;
        protected global::System.Web.UI.WebControls.GridView gvReport;
    }
}
